### ISSUE TITLE
您好，想问一下热门关注与每日一文的数据在哪里修改呢？能不能采集自己需要的内容，谢谢。

### ISSUE THREAD

**Issue by ekarlee** [dongyao8/dycms#12]
您好，想问一下热门关注与每日一文的数据在哪里修改呢？能不能采集自己需要的内容，谢谢。

**Comment by dongyao8** [comment]
热门关注的控制器在 https://github.com/dongyao8/dycms/blob/master/app/Http/Controllers/Common/HotnewsController.php

**Comment by dongyao8** [comment]
每日一文在：https://github.com/dongyao8/dycms/blob/master/app/Http/Controllers/Index/IndexController.php

**Comment by dongyao8** [comment]
你可以根据现有接口更换其他信息，下一个版本将会对这些功能页当做插件安装，目前只能手动替换

**Comment by ekarlee** [comment]
非常感谢
