### ISSUE TITLE
手动安装后没有admin后台怎么回事

### ISSUE THREAD

**Issue by xiangfeigao** [dongyao8/dycms#2]
手动安装运行php后没有后台，是不是没有装一些环境的问题

**Comment by dongyao8** [comment]
admin后台访问后，提示什么呢？出现首页能访问，其他二级页面无法访问的初步猜测可能是伪静态未设置，具体可以加一下Q群帮你看看

**Comment by xiangfeigao** [comment]
> admin后台访问后，提示什么呢？出现首页能访问，其他二级页面无法访问的初步猜测可能是伪静态未设置，具体可以加一下Q群帮你看看

已经解决了，伪静态模块安装后没有开启。谢谢
