### ISSUE TITLE
debian10环境警告

### ISSUE THREAD

**Issue by xiangfeigao** [dongyao8/dycms#4]
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

**Comment by dongyao8** [comment]
这几个可忽略
